version: '3.8'

services:
  wikipedia:
    restart: always
    build: ./wikipedia
    command: /app/wikipedia/cmd/web/main
    ports:
      - 4000:4000
    depends_on:
      - post_db
      - authorization


  post_db:
    restart: always
    build: ./post_db
    ports:
      - 60051:60051
    depends_on:
      - db

  authorization:
    restart: always
    build: ./authorization
    ports:
      - 60059:60059
    depends_on:
      - db



  db:
    restart: always
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data: